import steps.home_steps
import steps.side_menu.side_menu_steps
import steps.side_menu.login_in_steps
import steps.products.product_steps
import steps.cart.cart_steps
import steps.navbar.sort_by_steps
import steps.checkout.checkout_steps
import steps.checkout.checkout_complete_steps
import steps.checkout.checkout_payment_steps
import steps.checkout.checkout_review_steps